# Build stage

FROM node:18-alpine as build
WORKDIR /app

# Copy package files and npm config
COPY package*.json .npmrc ./

# Install all dependencies (including dev dependencies for build)
RUN npm ci --legacy-peer-deps

# Copy source code
COPY . .

# Build arguments for environment variables
ARG REACT_APP_API_BASE_URL
ARG REACT_APP_WS_URL
ARG REACT_APP_ENV=production
ARG REACT_APP_NAME=Dino
ARG REACT_APP_VERSION=1.0.0
ARG REACT_APP_DEBUG_MODE=false
ARG REACT_APP_ENABLE_THEME_TOGGLE=true
ARG REACT_APP_ENABLE_DEMO_MODE=false
ARG REACT_APP_ENABLE_ANALYTICS=true
ARG REACT_APP_ENABLE_QR_CODES=true
ARG REACT_APP_ENABLE_NOTIFICATIONS=true
ARG REACT_APP_API_TIMEOUT=30000
ARG REACT_APP_JWT_EXPIRY_HOURS=24
ARG REACT_APP_SESSION_TIMEOUT_MINUTES=60
ARG REACT_APP_MIN_PASSWORD_LENGTH=8
ARG REACT_APP_DEFAULT_THEME=light
ARG REACT_APP_ENABLE_ANIMATIONS=true
ARG REACT_APP_LOG_LEVEL=info
ARG REACT_APP_ENABLE_CONSOLE_LOGGING=false
# Additional feature flags
ARG REACT_APP_ENABLE_I18N=false
ARG REACT_APP_API_RATE_LIMIT=100
# Chart configuration
ARG REACT_APP_CHART_ANIMATION_INTERVAL=30000
ARG REACT_APP_CHART_ANIMATION_DURATION=1000
ARG REACT_APP_CHART_ANIMATION_EASING=easeInOutQuart
ARG REACT_APP_CHART_ANIMATIONS_ENABLED=true
ARG REACT_APP_CHART_AUTO_REFRESH_ENABLED=true
# Performance settings
ARG REACT_APP_ENABLE_IMAGE_OPTIMIZATION=true
ARG REACT_APP_ENABLE_SERVICE_WORKER=true
# Development settings (disabled in production)
ARG REACT_APP_ENABLE_HOT_RELOAD=false
ARG REACT_APP_GENERATE_SOURCEMAP=false

# Set environment variables for build
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL
ENV REACT_APP_WS_URL=$REACT_APP_WS_URL
ENV REACT_APP_ENV=$REACT_APP_ENV
ENV REACT_APP_NAME=$REACT_APP_NAME
ENV REACT_APP_VERSION=$REACT_APP_VERSION
ENV REACT_APP_DEBUG_MODE=$REACT_APP_DEBUG_MODE
ENV REACT_APP_ENABLE_THEME_TOGGLE=$REACT_APP_ENABLE_THEME_TOGGLE
ENV REACT_APP_ENABLE_DEMO_MODE=$REACT_APP_ENABLE_DEMO_MODE
ENV REACT_APP_ENABLE_ANALYTICS=$REACT_APP_ENABLE_ANALYTICS
ENV REACT_APP_ENABLE_QR_CODES=$REACT_APP_ENABLE_QR_CODES
ENV REACT_APP_ENABLE_NOTIFICATIONS=$REACT_APP_ENABLE_NOTIFICATIONS
ENV REACT_APP_API_TIMEOUT=$REACT_APP_API_TIMEOUT
ENV REACT_APP_JWT_EXPIRY_HOURS=$REACT_APP_JWT_EXPIRY_HOURS
ENV REACT_APP_SESSION_TIMEOUT_MINUTES=$REACT_APP_SESSION_TIMEOUT_MINUTES
ENV REACT_APP_MIN_PASSWORD_LENGTH=$REACT_APP_MIN_PASSWORD_LENGTH
ENV REACT_APP_DEFAULT_THEME=$REACT_APP_DEFAULT_THEME
ENV REACT_APP_ENABLE_ANIMATIONS=$REACT_APP_ENABLE_ANIMATIONS
ENV REACT_APP_LOG_LEVEL=$REACT_APP_LOG_LEVEL
ENV REACT_APP_ENABLE_CONSOLE_LOGGING=$REACT_APP_ENABLE_CONSOLE_LOGGING
# Additional feature flags
ENV REACT_APP_ENABLE_I18N=$REACT_APP_ENABLE_I18N
ENV REACT_APP_API_RATE_LIMIT=$REACT_APP_API_RATE_LIMIT
# Chart configuration
ENV REACT_APP_CHART_ANIMATION_INTERVAL=$REACT_APP_CHART_ANIMATION_INTERVAL
ENV REACT_APP_CHART_ANIMATION_DURATION=$REACT_APP_CHART_ANIMATION_DURATION
ENV REACT_APP_CHART_ANIMATION_EASING=$REACT_APP_CHART_ANIMATION_EASING
ENV REACT_APP_CHART_ANIMATIONS_ENABLED=$REACT_APP_CHART_ANIMATIONS_ENABLED
ENV REACT_APP_CHART_AUTO_REFRESH_ENABLED=$REACT_APP_CHART_AUTO_REFRESH_ENABLED
# Performance settings
ENV REACT_APP_ENABLE_IMAGE_OPTIMIZATION=$REACT_APP_ENABLE_IMAGE_OPTIMIZATION
ENV REACT_APP_ENABLE_SERVICE_WORKER=$REACT_APP_ENABLE_SERVICE_WORKER
# Development settings
ENV REACT_APP_ENABLE_HOT_RELOAD=$REACT_APP_ENABLE_HOT_RELOAD
ENV REACT_APP_GENERATE_SOURCEMAP=$REACT_APP_GENERATE_SOURCEMAP
ENV GENERATE_SOURCEMAP=false

# Build the app
RUN npm run build

# Production stage
FROM nginx:alpine

# Install curl for health checks
RUN apk add --no-cache curl

# Copy built app to nginx
COPY --from=build /app/build /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Set proper permissions for nginx
RUN chmod -R 755 /usr/share/nginx/html

EXPOSE 8080

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
 CMD curl -f http://localhost:8080/health || exit 1

CMD ["nginx", "-g", "daemon off;"]